version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db